Fix Faker.seed() TypeError by using seed_instance()
Faker.seed() is a classmethod accepting a single seed argument.
Passing self._fake as an argument caused:
TypeError: Faker.seed() takes from 1 to 2 positional arguments but 3 were given

Use self._fake.seed_instance(42) to seed the individual Faker instance.